### ISSUE TITLE
Change method for storing username and password in rdams pythong

### ISSUE THREAD

**Issue by DCSCHUS** [NCAR/rda-apps-clients#4]
Change method for storing username and password in rdams python -- currently saved to disk in plaintext.

**Comment by rpconroy** [comment]
The latest commit changed the python client to obfuscate plaintext username and password. Clearly this is not ideal, however even using cryptographically secure algorithms, the cypher would still need to be in the code unless provided by user or externally. Needless to say, modification of the code by a user should be encouraged if it does not fit their security needs.
