### ISSUE TITLE
Download empty folder

### ISSUE THREAD

**Issue by qloridant** [NCAR/rda-apps-clients#5]
I cloned the rda-apps-clients and used the rdams-client from the python3 folder.

Using a working RequestIndex (I managed to download my files from the web app), I tried : 
`python rdams-client.py -download LORIDANT407328`

and  I got  : 

`Starting Download.
Downloading Request to './rda_request_LORIDANT407328' directory.  Download Progress: [                    ] 0.0% `

This action created a folder but the folder is empty. 

Is this a know issue ?

- OS : Ubuntu 18
- Python : Python 3.7.4, from anaconda

**Comment by rpconroy** [comment]
Sorry for the incredibly late reply. A new version of the python client was released shortly after this issue was created that should likely address the problem. Feel free to open a new issue if you're still experiencing this or contact rdahelp@ucar.edu for more immediate help.
