### ISSUE TITLE
Control parameter 'datetype'='init' is ignored

### ISSUE THREAD

**Issue by elenatomasi** [NCAR/rda-apps-clients#6]
I am testing the rdams-client Python utility to submit subset requests on ds084.1 but I'm experiencing problems in getting the date range to include data based on model initialization date/time instead of valid date/time.

Here is the control info I'm submitting:
```
control = { 
         'dataset' : 'ds084.1',
         'date':'202003250000/to/202003250000',
         'datetype':'init',
         'param':'TMP/R H/ABS V',
         'level':'ISBL:850/700/500',
         'nlat':60,
         'slat':30,
         'elon':30,
         'wlon':-1,
         'product':'3-hour Forecast/6-hour Forecast/9-hour Forecast/12-hour Forecast'
         } 
```
Here is the list of files I'm getting:
```
gfs.0p25.2020032412.f012.grib2
gfs.0p25.2020032418.f006.grib2
```

Here is the list of files I'm expecting with the 'datetype'='init' parameter activated:
```
gfs.0p25.2020032500.f003.grib2   
gfs.0p25.2020032500.f006.grib2  
gfs.0p25.2020032500.f009.grib2  
gfs.0p25.2020032500.f012.grib2
```
So it looks like the control parameter 'datetype'='init' is ignored.
Manually submitting the following request from the GUI on the ucar webpage, which carries the exact same information as the control file,  I get the expected list of files. 
```
Subset details:

- Start date: 2020-03-25 00:00
- End date: 2020-03-25 00:00
- *Initialization (reference) dates
- Parameter(s):
    Absolute vorticity
    Relative humidity
    Temperature
- Vertical level(s):
    Isobaric surface: 500 mbar
    Isobaric surface: 700 mbar
    Isobaric surface: 850 mbar
- Product(s):
    3-hour Forecast
    6-hour Forecast
    9-hour Forecast
    12-hour Forecast
- Spatial subsetting (bounding box):
    Latitudes (top/bottom): 60 / 30
    Longitudes (left/right): -1 / 30
```

**Comment by rpconroy** [comment]
Hi, 
Thank you very much for pointing this out. The code was definitely skipping the `datetype` option, but I believe this has been fixed. Let me know if you're still experiencing problems, otherwise I'll close the issue in a week or so.

**Comment by elenatomasi** [comment]
Thank you! By now I can't see any new commit in the repo. Can you please check if you've pushed them? :)

**Comment by rpconroy** [comment]
The changes were made in another repo. This repositories scope is limited to client-side use cases.

**Comment by elenatomasi** [comment]
Ok! I just tried it out and it's working perfectly now! Thank you very much!
